# 🧠 Programación para Análisis de Datos – NumPy (Versión Extendida)
Este cuaderno contiene una guía detallada con ejercicios prácticos de NumPy, organizados por categoría funcional.
Incluye validación de datos, impresión de entrada y salida, y está diseñado para el aprendizaje progresivo.

In [3]:
from datagenerator import DataGenerator
from numpy_ejericicios import NumpyEjercicios
import numpy as np

In [4]:
data_gen = DataGenerator()
categorias=["niña", "bebe", "niño"] 
datos=data_gen.generar_datos_completos(n=50,categorias=categorias,x=4,limite_inferior=5,limite_superior=5000)

In [5]:
datos

array([['bebe', '4181', '0.20435551448709133', '-0.7428890918800537'],
       ['bebe', '3694', '0.3594356624608107', '-1.0995770053133525'],
       ['bebe', '291', '0.41939916488953877', '0.8363276587789169'],
       ['bebe', '943', '0.30503443351892645', '0.693581347955221'],
       ['niña', '559', '0.2681130465676095', '0.40436117051858317'],
       ['niño', '2966', '0.25881224463499586', '0.3436001942522252'],
       ['niño', '3711', '0.3719782966056562', '-1.5488818298149678'],
       ['niña', '70', '0.11165026398297628', '1.6513569638065235'],
       ['niño', '3617', '0.7304544922817413', '-0.07828035345598175'],
       ['niño', '459', '0.1520789244416133', '-0.3010639727684857'],
       ['bebe', '781', '0.9992974629171453', '0.5979034180411399'],
       ['bebe', '1397', '0.7018935960744531', '0.7722842068453272'],
       ['niña', '998', '0.7294154840455246', '-0.33469563204168823'],
       ['bebe', '21', '0.425207736896423', '1.8995062669139882'],
       ['niña', '3897', '0.25675

## Gardar y leer archivos

In [6]:
data_gen.escribir_datos(data=datos,tipo="txt",ruta="datos_in2")
#data_gen.leer_datos(tipo="txt",ruta="datos_in2")

### Numpy

#### Placeholders

In [7]:
np_ejer = NumpyEjercicios()
zeros = np.zeros((3,3))

zeros_dos = np_ejer.placeholder_zeros(x=10,y=10)
print(zeros)
print("******************")
print(zeros_dos)


📥 Entrada:
 np.zeros((10,10))
📤 Salida:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
📐 Tipo: <class 'numpy.ndarray'> | Forma: (10, 10)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
******************
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
np_ejer.inspeccionar_ndim(datos=datos)


📥 Entrada:
 [['bebe' '4181' '0.20435551448709133' '-0.7428890918800537']
 ['bebe' '3694' '0.3594356624608107' '-1.0995770053133525']
 ['bebe' '291' '0.41939916488953877' '0.8363276587789169']
 ['bebe' '943' '0.30503443351892645' '0.693581347955221']
 ['niña' '559' '0.2681130465676095' '0.40436117051858317']
 ['niño' '2966' '0.25881224463499586' '0.3436001942522252']
 ['niño' '3711' '0.3719782966056562' '-1.5488818298149678']
 ['niña' '70' '0.11165026398297628' '1.6513569638065235']
 ['niño' '3617' '0.7304544922817413' '-0.07828035345598175']
 ['niño' '459' '0.1520789244416133' '-0.3010639727684857']
 ['bebe' '781' '0.9992974629171453' '0.5979034180411399']
 ['bebe' '1397' '0.7018935960744531' '0.7722842068453272']
 ['niña' '998' '0.7294154840455246' '-0.33469563204168823']
 ['bebe' '21' '0.425207736896423' '1.8995062669139882']
 ['niña' '3897' '0.25675210212906374' '-0.7167684850689735']
 ['bebe' '906' '0.8819245188798345' '0.09426531963264342']
 ['niña' '1573' '0.20864932431096084' '

2

In [11]:
np_ejer.inspeccionar_size(datos=zeros)
#np_ejer.inspeccionar_size(datos=datos)


📥 Entrada:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
📤 Salida:
 9
📐 Tipo: <class 'int'> | Forma: escalar


9