# 🧠 Programación para Análisis de Datos – NumPy (Versión Extendida)
Este cuaderno contiene una guía detallada con ejercicios prácticos de NumPy, organizados por categoría funcional.
Incluye validación de datos, impresión de entrada y salida, y está diseñado para el aprendizaje progresivo.

In [1]:
from datagenerator import DataGenerator
from numpy_ejericicios import NumpyEjercicios
import numpy as np

In [2]:
data_gen = DataGenerator()
categorias=["niña", "bebe", "niño"] 
datos=data_gen.generar_datos_completos(n=50,categorias=categorias,x=4,limite_inferior=5,limite_superior=5000)

In [3]:
datos

array([['bebe', '3220', '0.4307174891723806', '0.5984823229316127'],
       ['niña', '1380', '0.6778346997398381', '0.00872897554440561'],
       ['niño', '566', '0.43541130735724076', '0.8496162932950198'],
       ['niño', '3078', '0.3149798272849067', '-1.1662401361795725'],
       ['niña', '532', '0.753523697267791', '2.1106109305307874'],
       ['bebe', '3836', '0.26090903504182217', '0.10527428324036382'],
       ['niña', '1322', '0.512856203962888', '-0.2164071044459521'],
       ['niña', '1032', '0.9774308293678657', '-0.3620246357013975'],
       ['bebe', '1670', '0.7415474302493832', '0.10400607373438613'],
       ['niña', '1408', '0.7195611644093864', '0.8005977205269466'],
       ['niño', '4592', '0.3275004049624819', '-0.5267083620221211'],
       ['niño', '1216', '0.5820674761985718', '-0.488724819598438'],
       ['niña', '981', '0.8660170919171304', '0.10290318715768258'],
       ['niña', '1269', '0.5006233209051555', '0.4749710248814519'],
       ['niño', '1173', '0.86

## Gardar y leer archivos

In [4]:
data_gen.escribir_datos(data=datos,tipo="txt",ruta="datos_in2")
#data_gen.leer_datos(tipo="txt",ruta="datos_in2")

### Numpy

#### Placeholders

In [5]:
np_ejer = NumpyEjercicios()
zeros = np.zeros((3,3))

zeros_dos = np_ejer.placeholder_zeros(x=10,y=10)
print(zeros)
print("******************")
print(zeros_dos)


📥 Entrada:
 np.zeros((10,10))
📤 Salida:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
📐 Tipo: <class 'numpy.ndarray'> | Forma: (10, 10)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
******************
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
np_ejer.inspeccionar_ndim(datos=datos)


📥 Entrada:
 [['bebe' '3220' '0.4307174891723806' '0.5984823229316127']
 ['niña' '1380' '0.6778346997398381' '0.00872897554440561']
 ['niño' '566' '0.43541130735724076' '0.8496162932950198']
 ['niño' '3078' '0.3149798272849067' '-1.1662401361795725']
 ['niña' '532' '0.753523697267791' '2.1106109305307874']
 ['bebe' '3836' '0.26090903504182217' '0.10527428324036382']
 ['niña' '1322' '0.512856203962888' '-0.2164071044459521']
 ['niña' '1032' '0.9774308293678657' '-0.3620246357013975']
 ['bebe' '1670' '0.7415474302493832' '0.10400607373438613']
 ['niña' '1408' '0.7195611644093864' '0.8005977205269466']
 ['niño' '4592' '0.3275004049624819' '-0.5267083620221211']
 ['niño' '1216' '0.5820674761985718' '-0.488724819598438']
 ['niña' '981' '0.8660170919171304' '0.10290318715768258']
 ['niña' '1269' '0.5006233209051555' '0.4749710248814519']
 ['niño' '1173' '0.8699887784752417' '-2.3837021019773506']
 ['bebe' '1917' '0.25495494387834083' '-1.630039638547194']
 ['bebe' '3277' '0.5669639068474295'

2

In [11]:
np_ejer.inspeccionar_size(datos=zeros)
#np_ejer.inspeccionar_size(datos=datos)


📥 Entrada:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
📤 Salida:
 9
📐 Tipo: <class 'int'> | Forma: escalar


9

In [42]:
dimenciones = [1,2,3,4]
dos_dimenciones= np.array([[1,2,3],[4,5,6]])
print(dos_dimenciones[:,:1])

[[1]
 [4]]


In [27]:
datos[:,1:]

array([['3220', '0.4307174891723806', '0.5984823229316127'],
       ['1380', '0.6778346997398381', '0.00872897554440561'],
       ['566', '0.43541130735724076', '0.8496162932950198'],
       ['3078', '0.3149798272849067', '-1.1662401361795725'],
       ['532', '0.753523697267791', '2.1106109305307874'],
       ['3836', '0.26090903504182217', '0.10527428324036382'],
       ['1322', '0.512856203962888', '-0.2164071044459521'],
       ['1032', '0.9774308293678657', '-0.3620246357013975'],
       ['1670', '0.7415474302493832', '0.10400607373438613'],
       ['1408', '0.7195611644093864', '0.8005977205269466'],
       ['4592', '0.3275004049624819', '-0.5267083620221211'],
       ['1216', '0.5820674761985718', '-0.488724819598438'],
       ['981', '0.8660170919171304', '0.10290318715768258'],
       ['1269', '0.5006233209051555', '0.4749710248814519'],
       ['1173', '0.8699887784752417', '-2.3837021019773506'],
       ['1917', '0.25495494387834083', '-1.630039638547194'],
       ['3277', '

In [ ]:
np_ejer.multiplicacion_elemento(datos=datos,3.65)
#np_ejer.suma_array(zeros,3.65)


📥 Entrada:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
📤 Salida:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
📐 Tipo: <class 'numpy.ndarray'> | Forma: (3, 3)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])