# 🧠 Programación para Análisis de Datos – NumPy (Versión Extendida)
Este cuaderno contiene una guía detallada con ejercicios prácticos de NumPy, organizados por categoría funcional.
Incluye validación de datos, impresión de entrada y salida, y está diseñado para el aprendizaje progresivo.

In [35]:
from datagenerator import DataGenerator
from numpy_ejericicios import NumpyEjercicios
import numpy as np

In [36]:
data_gen = DataGenerator()
categorias=["niña", "bebe", "niño"] 
datos=data_gen.generar_datos_completos(n=50,categorias=categorias,x=4,limite_inferior=5,limite_superior=5000)

In [37]:
datos

array([['bebe', '2039', '0.21419585246799067', '0.4671264974519602'],
       ['niño', '3520', '0.1612855026023633', '0.41145008138787564'],
       ['bebe', '4183', '0.1762423801060956', '-0.3526021731184788'],
       ['niño', '2712', '0.4492687814714802', '1.1187800813378683'],
       ['bebe', '690', '0.5572534805717365', '-1.8502980592620029'],
       ['niña', '1113', '0.4651685563589567', '-0.636503734755461'],
       ['niña', '3567', '0.030940573752384237', '-0.15352585494596316'],
       ['niña', '4112', '0.15880417689296344', '-1.1478598742527721'],
       ['niño', '3821', '0.2861663256346253', '-0.811102115812381'],
       ['bebe', '3900', '0.7931847188252017', '-1.6707989055124406'],
       ['niño', '282', '0.6598817899542283', '1.7422335921912067'],
       ['niña', '1836', '0.6382554168643552', '0.11623234469731837'],
       ['niña', '4123', '0.7357120868387752', '-1.586443119954883'],
       ['bebe', '4827', '0.36310839041907406', '-0.11321894357437826'],
       ['bebe', '4673

## Gardar y leer archivos

In [38]:
data_gen.escribir_datos(data=datos,tipo="txt",ruta="datos_in2")
#data_gen.leer_datos(tipo="txt",ruta="datos_in2")

### Numpy

#### Placeholders

In [39]:
np_ejer = NumpyEjercicios()
zeros = np.zeros((3,3))

zeros_dos = np_ejer.placeholder_zeros(x=10,y=10)
print(zeros)
print("******************")
print(zeros_dos)


📥 Entrada:
 np.zeros((10,10))
📤 Salida:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
📐 Tipo: <class 'numpy.ndarray'> | Forma: (10, 10)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
******************
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
np_ejer.inspeccionar_ndim(datos=datos)


📥 Entrada:
 [['bebe' '2039' '0.21419585246799067' '0.4671264974519602']
 ['niño' '3520' '0.1612855026023633' '0.41145008138787564']
 ['bebe' '4183' '0.1762423801060956' '-0.3526021731184788']
 ['niño' '2712' '0.4492687814714802' '1.1187800813378683']
 ['bebe' '690' '0.5572534805717365' '-1.8502980592620029']
 ['niña' '1113' '0.4651685563589567' '-0.636503734755461']
 ['niña' '3567' '0.030940573752384237' '-0.15352585494596316']
 ['niña' '4112' '0.15880417689296344' '-1.1478598742527721']
 ['niño' '3821' '0.2861663256346253' '-0.811102115812381']
 ['bebe' '3900' '0.7931847188252017' '-1.6707989055124406']
 ['niño' '282' '0.6598817899542283' '1.7422335921912067']
 ['niña' '1836' '0.6382554168643552' '0.11623234469731837']
 ['niña' '4123' '0.7357120868387752' '-1.586443119954883']
 ['bebe' '4827' '0.36310839041907406' '-0.11321894357437826']
 ['bebe' '4673' '0.4740517217673371' '0.8907350176722119']
 ['niño' '458' '0.35550289929065315' '-0.7180855747104804']
 ['bebe' '1596' '0.9122350819

2

In [41]:
np_ejer.inspeccionar_size(datos=zeros)
#np_ejer.inspeccionar_size(datos=datos)


📥 Entrada:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
📤 Salida:
 9
📐 Tipo: <class 'int'> | Forma: escalar


9

In [42]:
dimenciones = [1,2,3,4]
dos_dimenciones= np.array([[1,2,3],[4,5,6]])
print(dos_dimenciones[:,:1])

[[1]
 [4]]


In [43]:
datos[:,1:]

array([['2039', '0.21419585246799067', '0.4671264974519602'],
       ['3520', '0.1612855026023633', '0.41145008138787564'],
       ['4183', '0.1762423801060956', '-0.3526021731184788'],
       ['2712', '0.4492687814714802', '1.1187800813378683'],
       ['690', '0.5572534805717365', '-1.8502980592620029'],
       ['1113', '0.4651685563589567', '-0.636503734755461'],
       ['3567', '0.030940573752384237', '-0.15352585494596316'],
       ['4112', '0.15880417689296344', '-1.1478598742527721'],
       ['3821', '0.2861663256346253', '-0.811102115812381'],
       ['3900', '0.7931847188252017', '-1.6707989055124406'],
       ['282', '0.6598817899542283', '1.7422335921912067'],
       ['1836', '0.6382554168643552', '0.11623234469731837'],
       ['4123', '0.7357120868387752', '-1.586443119954883'],
       ['4827', '0.36310839041907406', '-0.11321894357437826'],
       ['4673', '0.4740517217673371', '0.8907350176722119'],
       ['458', '0.35550289929065315', '-0.7180855747104804'],
       ['1

In [44]:
#datos_dos=datos[:,1:]
#print(datos_dos)
np_ejer.multiplicacion_elemento(datos=datos[:,1:].astype(float),valor=1)
#np_ejer.suma_array(zeros,3.65)


📥 Entrada:
 [[ 2.03900000e+03  2.14195852e-01  4.67126497e-01]
 [ 3.52000000e+03  1.61285503e-01  4.11450081e-01]
 [ 4.18300000e+03  1.76242380e-01 -3.52602173e-01]
 [ 2.71200000e+03  4.49268781e-01  1.11878008e+00]
 [ 6.90000000e+02  5.57253481e-01 -1.85029806e+00]
 [ 1.11300000e+03  4.65168556e-01 -6.36503735e-01]
 [ 3.56700000e+03  3.09405738e-02 -1.53525855e-01]
 [ 4.11200000e+03  1.58804177e-01 -1.14785987e+00]
 [ 3.82100000e+03  2.86166326e-01 -8.11102116e-01]
 [ 3.90000000e+03  7.93184719e-01 -1.67079891e+00]
 [ 2.82000000e+02  6.59881790e-01  1.74223359e+00]
 [ 1.83600000e+03  6.38255417e-01  1.16232345e-01]
 [ 4.12300000e+03  7.35712087e-01 -1.58644312e+00]
 [ 4.82700000e+03  3.63108390e-01 -1.13218944e-01]
 [ 4.67300000e+03  4.74051722e-01  8.90735018e-01]
 [ 4.58000000e+02  3.55502899e-01 -7.18085575e-01]
 [ 1.59600000e+03  9.12235082e-01  6.09276507e-01]
 [ 3.28000000e+02  8.19987147e-01 -1.82185826e-01]
 [ 3.33300000e+03  6.52831599e-02  1.49401476e+00]
 [ 6.14000000e+02 

array([[ 2.03900000e+03,  2.14195852e-01,  4.67126497e-01],
       [ 3.52000000e+03,  1.61285503e-01,  4.11450081e-01],
       [ 4.18300000e+03,  1.76242380e-01, -3.52602173e-01],
       [ 2.71200000e+03,  4.49268781e-01,  1.11878008e+00],
       [ 6.90000000e+02,  5.57253481e-01, -1.85029806e+00],
       [ 1.11300000e+03,  4.65168556e-01, -6.36503735e-01],
       [ 3.56700000e+03,  3.09405738e-02, -1.53525855e-01],
       [ 4.11200000e+03,  1.58804177e-01, -1.14785987e+00],
       [ 3.82100000e+03,  2.86166326e-01, -8.11102116e-01],
       [ 3.90000000e+03,  7.93184719e-01, -1.67079891e+00],
       [ 2.82000000e+02,  6.59881790e-01,  1.74223359e+00],
       [ 1.83600000e+03,  6.38255417e-01,  1.16232345e-01],
       [ 4.12300000e+03,  7.35712087e-01, -1.58644312e+00],
       [ 4.82700000e+03,  3.63108390e-01, -1.13218944e-01],
       [ 4.67300000e+03,  4.74051722e-01,  8.90735018e-01],
       [ 4.58000000e+02,  3.55502899e-01, -7.18085575e-01],
       [ 1.59600000e+03,  9.12235082e-01

### Mayor menor que ?

In [45]:
type (datos)

numpy.ndarray

In [46]:
#datos[:,1:].astype(float)>2
datos[:,1:].astype(float)==4641

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [Fa

In [47]:
np.array_equal(dimenciones,dimenciones.copy())

True

# funciones de agregacion

In [55]:
#datos[:,2:3].astype(float)
#datos[:,1:2].astype(float).sum()
datos[:,1:2].astype(float).mean() # promedio
datos[:,1:2].astype(float).max() # maximo
datos[:,1:2].astype(float).min() # maximo

np.float64(282.0)

![alt text](hq720.jpg)

# manipulacion de arreglos y matrices